{{- if and .Values.client.metrics.enable .Values.client.metrics.podMonitor.enable }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "dragonfly.client.fullname" . }}
  labels:
    app: {{ template "dragonfly.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.client.name }}
    {{- if .Values.client.metrics.podMonitor.additionalLabels }}
{{ toYaml .Values.client.metrics.podMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
  - port: {{ .Values.client.config.metrics.port }}
    path: /metrics
    {{- if .Values.client.metrics.podMonitor.interval }}
    interval: {{ .Values.client.metrics.podMonitor.interval }}
    {{- end }}
    {{- if .Values.client.metrics.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.client.metrics.podMonitor.scrapeTimeout }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "dragonfly.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.client.name }}
{{- end }}
