apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nydus-snapshotter.fullname" . }}
  labels:
    app: {{ template "nydus-snapshotter.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.nydusSnapshotter.name }}
data:
  config.json: |-
    {
      "device": {
        "backend": {
          "type": "registry",
          "config": {
          {{- if .Values.dragonfly.enable }}
            "mirrors": [
              {{ mustToJson .Values.dragonfly.mirrorConfig | indent 8 }}
            ],
          {{- end }}
            "scheme": "https",
            "skip_verify": false,
            "timeout": 10,
            "connect_timeout": 10,
            "retry_limit": 2
          }
        },
        "cache": {
          "type": "blobcache",
          "config": {
            "work_dir": "/var/lib/nydus/cache/"
          }
        }
      },
      "mode": "direct",
      "digest_validate": false,
      "iostats_files": false,
      "enable_xattr": true,
      "fs_prefetch": {
        "enable": true,
        "threads_count": 10,
        "merging_size": 131072,
        "bandwidth_rate": 1048576
      }
    }
