{{- if .Values.dfdaemon.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.dfdaemon.fullname" . }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.dfdaemon.name }}
data:
  dfget.yaml: |-
    aliveTime: {{ .Values.dfdaemon.config.aliveTime }}
    gcInterval: {{ .Values.dfdaemon.config.gcInterval }}
    keepStorage: {{ .Values.dfdaemon.config.keepStorage }}
    dataDir: {{ .Values.dfdaemon.config.dataDir }}
    workDir: {{ .Values.dfdaemon.config.dataDir }}
    verbose: {{ .Values.dfdaemon.config.verbose }}
    {{- if .Values.dfdaemon.config.jaeger }}
    jaeger: {{ .Values.dfdaemon.config.jaeger }}
    {{- else if .Values.jaeger.enable }}
    jaeger: http://jaeger-all-in-one-collector.{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }}:14268/api/traces
    {{- end }}
    scheduler:
      netAddrs:
      {{- $count := .Values.scheduler.replicas | int}}
      {{- range $i, $x := until $count }}
      - type: tcp
        addr: {{template "dragonfly.scheduler.fullname" $ }}-{{$i}}.{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }}:{{ $.Values.scheduler.service.port }}
      {{- end }}
      scheduleTimeout: 5m
    host:
{{ toYaml .Values.dfdaemon.config.host | indent 6 }}
    download:
{{ toYaml .Values.dfdaemon.config.download | indent 6 }}
    upload:
{{ toYaml .Values.dfdaemon.config.upload | indent 6 }}
    storage:
{{ toYaml .Values.dfdaemon.config.storage | indent 6 }}
    proxy:
      defaultFilter: {{ .Values.dfdaemon.config.proxy.defaultFilter }}
      tcpListen:
    {{- if not .Values.dfdaemon.hostNetwork }}
        namespace: {{ .Values.dfdaemon.config.proxy.tcpListen.namespace }}
    {{- end }}
        listen: {{ .Values.dfdaemon.config.proxy.tcpListen.listen }}
        port: {{ .Values.dfdaemon.containerPort }}
      security:
{{ toYaml .Values.dfdaemon.config.proxy.security | indent 8 }}
      registryMirror:
{{ toYaml .Values.dfdaemon.config.proxy.registryMirror | indent 8 }}
      proxies:
{{ toYaml .Values.dfdaemon.config.proxy.proxies | indent 8 }}
      {{- if .Values.containerRuntime.docker.enable }}
      hijackHTTPS:
        cert: /etc/dragonfly-ca/cacert.pem
        key: /etc/dragonfly-ca/cakey.pem
        hosts:
        - regx: .*
          insecure: {{ .Values.containerRuntime.docker.insecure }}
        {{- if and .Values.containerRuntime.docker.injectHosts (not .Values.containerRuntime.docker.restart) }}
        {{- if not .Values.dfdaemon.hostNetwork }}
        sni:
        - listen: 127.0.0.1
          port: 443
          {{- if not .Values.dfdaemon.hostNetwork }}
          namespace: {{ .Values.dfdaemon.config.proxy.tcpListen.namespace }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
