{{- if .Values.injector.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.fullname" . }}-injector-config
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: injector
data:
  config.yaml: |
    initContainerImage:
{{ toYaml .Values.injector.initContainerImage | indent 6 }}
{{- end }}
