{{- if .Values.injector.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "dragonfly.fullname" . }}-injector
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: injector
    app.kubernetes.io/name: dragonfly-injector
{{- end }}
