{{- if and .Values.cdn.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "dragonfly.cdn.fullname" . }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.cdn.name }}
spec:
  accessModes:
    - {{ .Values.cdn.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.cdn.persistence.size | quote }}
{{- if .Values.cdn.persistence.storageClass }}
{{- if (eq "-" .Values.cdn.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.cdn.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
