{{- if .Values.triton.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dragonfly.triton.fullname" . }}-credentials
type: Opaque
data:
  region: {{ .Values.triton.aws.region | b64enc | quote }}
  accessKeyID: {{ .Values.triton.aws.accessKeyID | b64enc | quote }}
  secretAccessKey: {{ .Values.triton.aws.secretAccessKey | b64enc | quote }}
{{- end}}
