{{- if .Values.triton.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dragonfly.triton.fullname" . }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.triton.name }}
  annotations:
  {{- if .Values.triton.deploymentAnnotations }}
{{ toYaml .Values.triton.deploymentAnnotations | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.triton.updateStrategy }}
  updateStrategy:
{{ toYaml .Values.triton.updateStrategy | indent 4 }}
  {{- end }}
  replicas: {{ .Values.triton.replicas }}
  selector:
    matchLabels:
      app: {{ template "dragonfly.fullname" . }}
      component: {{ .Values.triton.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "dragonfly.fullname" . }}
        component: {{ .Values.triton.name }}
        release: {{ .Release.Name }}
      annotations:
        checksum/serect: {{ include (print $.Template.BasePath "/triton/triton-secrets.yaml") . | sha256sum }}
      {{- if .Values.triton.podAnnotations }}
{{ toYaml .Values.triton.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- with .Values.triton.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.triton.tolerations }}
      tolerations:
{{ toYaml .Values.triton.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.triton.affinity }}
      affinity:
{{ toYaml .Values.triton.affinity | indent 8 }}
      {{- end }}
      {{- if quote .Values.triton.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.triton.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.triton.priorityClassName) }}
      priorityClassName: {{ .Values.triton.priorityClassName }}
      {{- end }}
      {{- with .Values.triton.image.pullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.triton.hostAliases }}
      hostAliases:
{{ toYaml .Values.triton.hostAliases | indent 8 }}
      {{- end }}
      containers:
        - name: triton
          image: {{ template "triton.image" . }}
          imagePullPolicy: {{ .Values.triton.image.pullPolicy | quote}}
          args: ["tritonserver", "--model-store={{ .Values.triton.modelRepositoryPath }}",
                 "--model-control-mode=poll",
                 "--repository-poll-secs=5"]
          env:
            {{- if .Values.triton.maxProcs }}
            - name: GOMAXPROCS
              value: {{ .Values.triton.maxProcs }}
            {{- end }}
            - name: DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "dragonfly.triton.fullname" . }}-credentials
                  key: region
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "dragonfly.triton.fullname" . }}-credentials
                  key: accessKeyID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "dragonfly.triton.fullname" . }}-credentials
                  key: secretAccessKey
          ports:
            - containerPort: {{ .Values.triton.restPort }}
              name: http-rest
              protocol: TCP
            - containerPort: {{ .Values.triton.grpcPort }}
              name: http-grpc
              protocol: TCP
            - containerPort: 8002
              name: http-metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: http-rest
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: http-rest
            initialDelaySeconds: 15
            periodSeconds: 10
{{- end}}
