{{- if .Values.seedClient.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dragonfly.seedClient.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app: {{ template "dragonfly.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.seedClient.name }}
data:
  dfdaemon.yaml: |-
    {{- if ne (lower .Values.grpcAuth.mode) "disabled" }}
    grpcAuth:
{{ include "dragonfly.grpcAuth.config" . | indent 6 }}
    {{- end }}
    host:
{{ toYaml .Values.seedClient.config.host | indent 6 }}
    server:
{{ toYaml .Values.seedClient.config.server | indent 6 }}
    download:
{{ toYaml .Values.seedClient.config.download | indent 6 }}
    upload:
{{ toYaml .Values.seedClient.config.upload | indent 6 }}
    {{- if .Values.manager.enable }}
    manager:
      addr: http://{{ template "dragonfly.manager.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.manager.grpcPort }}
    {{- else if .Values.externalManager.host }}
    manager:
      addr: http://{{ .Values.externalManager.host }}:{{ .Values.externalManager.grpcPort }}
    {{- end }}
    scheduler:
{{ toYaml .Values.seedClient.config.scheduler | indent 6 }}
    seedPeer:
{{ toYaml .Values.seedClient.config.seedPeer | indent 6 }}
    dynconfig:
{{ toYaml .Values.seedClient.config.dynconfig | indent 6 }}
    storage:
{{ toYaml .Values.seedClient.config.storage | indent 6 }}
    gc:
{{ toYaml .Values.seedClient.config.gc | indent 6 }}
    proxy:
{{ toYaml .Values.seedClient.config.proxy | indent 6 }}
    health:
{{ toYaml .Values.seedClient.config.health | indent 6 }}
    metrics:
{{ toYaml .Values.seedClient.config.metrics | indent 6 }}
    stats:
{{ toYaml .Values.seedClient.config.stats | indent 6 }}
    tracing:
{{ toYaml .Values.seedClient.config.tracing | indent 6 }}
    backend:
{{ toYaml .Values.seedClient.config.backend | indent 6 }}
    network:
{{ toYaml .Values.seedClient.config.network | indent 6 }}
  {{- if not (include "dragonfly.manager.enable" .) }}
  dynconfig.yaml: |-
    scheduler:
      {{- if .Values.seedClient.dynconfig.scheduler.addr }}
      addr: {{ .Values.seedClient.dynconfig.scheduler.addr }}
      {{- else }}
      addr: {{ template "dragonfly.scheduler.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.scheduler.config.server.port }}
      {{- end }}
      {{- if .Values.seedClient.dynconfig.scheduler.addrs }}
      addrs:
{{ toYaml .Values.seedClient.dynconfig.scheduler.addrs | indent 6 }}
      {{- end }}
    {{- if .Values.seedClient.dynconfig.clientConfig }}
    clientConfig:
{{ toYaml .Values.seedClient.dynconfig.clientConfig | indent 6 }}
    {{- end }}
    {{- if .Values.seedClient.dynconfig.seedClientConfig }}
    seedClientConfig:
{{ toYaml .Values.seedClient.dynconfig.seedClientConfig | indent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
