name: PR Label

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

permissions:
  contents: read

jobs:
  classify:
    name: Classify PR
    runs-on: ubuntu-latest
    steps:
      - name: PR impact specified
        uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5.5
        with:
          mode: exactly
          count: 1
          labels: 'bug, enhancement, documentation, dependencies'
